# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(related_name='userfave', to='class_app.User'),
        ),
    ]
