# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='apptime',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
