# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20180226_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='apptime',
            field=models.TimeField(),
        ),
    ]
